<?php
/**
 * @file
 * footer.features.menu_links.inc
 */

/**
 * Implements hook_menu_default_menu_links().
 */
function footer_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: menu-footer-menu_avis-de-non-responsabilit:node/2383
  $menu_links['menu-footer-menu_avis-de-non-responsabilit:node/2383'] = array(
    'menu_name' => 'menu-footer-menu',
    'link_path' => 'node/2383',
    'router_path' => 'node/%',
    'link_title' => 'Avis de non-responsabilité',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-footer-menu_avis-de-non-responsabilit:node/2383',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'language' => 'fr',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-footer-menu_confidentialit:node/2428
  $menu_links['menu-footer-menu_confidentialit:node/2428'] = array(
    'menu_name' => 'menu-footer-menu',
    'link_path' => 'node/2428',
    'router_path' => 'node/%',
    'link_title' => 'Confidentialité',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-footer-menu_confidentialit:node/2428',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
    'language' => 'fr',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-footer-menu_disclaimer:node/2383
  $menu_links['menu-footer-menu_disclaimer:node/2383'] = array(
    'menu_name' => 'menu-footer-menu',
    'link_path' => 'node/2383',
    'router_path' => 'node/%',
    'link_title' => 'Disclaimer',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-footer-menu_disclaimer:node/2383',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'language' => 'en',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-footer-menu_e-updates:node/4873
  $menu_links['menu-footer-menu_e-updates:node/4873'] = array(
    'menu_name' => 'menu-footer-menu',
    'link_path' => 'node/4873',
    'router_path' => 'node/%',
    'link_title' => 'E-Updates',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-footer-menu_e-updates:node/4873',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -41,
    'customized' => 1,
    'language' => 'en',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-footer-menu_log-out:user/logout
  $menu_links['menu-footer-menu_log-out:user/logout'] = array(
    'menu_name' => 'menu-footer-menu',
    'link_path' => 'user/logout',
    'router_path' => 'user/logout',
    'link_title' => 'Log out',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-footer-menu_log-out:user/logout',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'language' => 'en',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-footer-menu_privacy-notice:node/2428
  $menu_links['menu-footer-menu_privacy-notice:node/2428'] = array(
    'menu_name' => 'menu-footer-menu',
    'link_path' => 'node/2428',
    'router_path' => 'node/%',
    'link_title' => 'Privacy Notice',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-footer-menu_privacy-notice:node/2428',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'language' => 'en',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-footer-menu_rate-the-hr-portal:node/2901
  $menu_links['menu-footer-menu_rate-the-hr-portal:node/2901'] = array(
    'menu_name' => 'menu-footer-menu',
    'link_path' => 'node/2901',
    'router_path' => 'node/%',
    'link_title' => 'Rate the HR Portal',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-footer-menu_rate-the-hr-portal:node/2901',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -43,
    'customized' => 1,
    'language' => 'en',
    'menu_links_customized' => 1,
  );
  // Exported menu link: menu-footer-menu_valuer-le-portail:node/2901
  $menu_links['menu-footer-menu_valuer-le-portail:node/2901'] = array(
    'menu_name' => 'menu-footer-menu',
    'link_path' => 'node/2901',
    'router_path' => 'node/%',
    'link_title' => 'Évaluer le Portail',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'alter' => TRUE,
      'identifier' => 'menu-footer-menu_valuer-le-portail:node/2901',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -42,
    'customized' => 1,
    'language' => 'fr',
    'menu_links_customized' => 1,
  );
  // Translatables
  // Included for use with string extractors like potx.
  t('Avis de non-responsabilité');
  t('Confidentialité');
  t('Disclaimer');
  t('E-Updates');
  t('Log out');
  t('Privacy Notice');
  t('Rate the HR Portal');
  t('Évaluer le Portail');


  return $menu_links;
}
